# Generated by Django 4.0.6 on 2022-07-27 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('familiar', '0002_remove_familiar_anio_nac'),
    ]

    operations = [
        migrations.AddField(
            model_name='familiar',
            name='edad',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
