# Generated by Django 4.0.6 on 2022-07-27 05:08

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('familiar', '0003_familiar_edad'),
    ]

    operations = [
        migrations.AddField(
            model_name='familiar',
            name='fecha_nac',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
