# Generated by Django 4.0.6 on 2022-07-27 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('familiar', '0005_alter_familiar_fecha_nac'),
    ]

    operations = [
        migrations.AlterField(
            model_name='familiar',
            name='fecha_nac',
            field=models.DateField(),
        ),
    ]
